config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: "pages#dashboard", as: "dashboard"

  resources :patterns do
    resources :reviews, only: [:new, :create, :edit, :update]
  end
  get 'patterns/:id/steps', to: "patterns#show_steps", as: "pattern_steps"
  get 'patterns/:id/instructions', to: "patterns#show_instructions", as: "pattern_instructions"

  get 'patterns/:id/instructions/new', to: "instructions#new", as: "new_instruction"
  post 'patterns/:id/instructions', to: "instructions#create", as: "create_instruction"
  post 'patterns/:id/categories', to: "categories#create", as: "create_category"

  get 'orders/:order_id/customised_instructions/new', to: "customised_instructions#new", as: "new_customised_instruction"
  post 'orders/:order_id/customised_instructions', to: "customised_instructions#create", as: "order_customised_instructions"

  resources :customised_instructions, only: [:edit, :show, :destroy] do
    resources :custom_categories, only: [:new, :create]
  end

  resources :customised_instruction_steps, only: [:edit, :update]
  get 'customised_instruction_steps/:id/', to: "customised_instruction_steps#show", as: "customised_instruction_steps"

  resources :custom_categories, only: [:update, :destroy]

  patch 'customised_instruction_steps/:id/category', to: "customised_instruction_steps#update_category"

  get 'carts/show'
  get 'carts/:id' => "carts#show", as: "cart"
  post 'carts/checkout' => "carts#checkout", as: "checkout_cart"
  delete 'carts/:id' => "carts#destroy"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  resources :reviews, only: [:destroy]
end

app/models/customised_instruction.rb
class CustomisedInstruction < ApplicationRecord
  belongs_to :order
  has_many :customised_instruction_steps, dependent: :destroy
  has_many :custom_categories, -> { order(position: :asc) }, dependent: :destroy
  accepts_nested_attributes_for :custom_categories
end

app/controllers/customised_instructions_controller.rb
class CustomisedInstructionsController < ApplicationController
  def show
    @customised_instruction = CustomisedInstruction.find(params[:id])
    @customised_instruction_steps_by_category = @customised_instruction.custom_categories
  end

  def edit
    @customised_instruction = CustomisedInstruction.find(params[:id])
    @customised_instruction_steps_by_category = @customised_instruction.custom_categories
    @custom_category = CustomCategory.new
  end

  def update
    @customised_instruction = CustomisedInstruction.find(params[:id])
    @customised_instruction.update(customised_instruction_params)
    redirect_to customised_instruction_path(@customised_instruction)
  end

  def new
    @order = Order.find(params[:order_id])
    @customised_instruction = CustomisedInstruction.new
  end

  def create
    @order = Order.find(params[:order_id])
    @customised_instruction = CustomisedInstruction.new(customised_instruction_params)
    @customised_instruction.order_id = @order.id
    # make the customised instruction that it's going to be scoped to
    @customised_instruction.save
    # make the customised instruction categories
    @order.pattern.categories.each do |category|
      @newcategory = CustomCategory.new(
        customised_instruction: @customised_instruction,
        name: category.name,
        position: category.position
      )
      @newcategory.save!
      # make the customised instruction steps for each category
      category.instructions.each do |instruction_step|
        newstep = CustomisedInstructionStep.new(
          customised_instruction: @customised_instruction,
          custom_category: @newcategory,
          instruction: instruction_step,
          position: instruction_step.position
        )
        newstep.save!
      end
    end
    redirect_to edit_customised_instruction_path(@customised_instruction)
  end

  def destroy
    @customised_instruction = CustomisedInstruction.find(params[:id])
    @pattern = @customised_instruction.order.pattern
    @customised_instruction.destroy
    redirect_to pattern_instructions_path(@pattern)
  end

  private

  def customised_instruction_params
    params.require(:customised_instruction).permit(:name)
  end
end

app/views/customised_instructions/edit.html.erb
<div style="max-width: 800px; margin: 0 auto">
  <h2> Customising instructions <h2>
  <%= render "shared/pattern_bar", pattern: @customised_instruction.order.pattern %>
  <h3> Select the sections you want</h3>
  <div class="accordion">
    <% @customised_instruction.custom_categories.each_with_index do |category, index| %>
      <div class="d-flex justify-content-between align-items-center">
        <%= turbo_frame_tag dom_id(category) do %>
          <div class="p-3">
            <%= link_to custom_category_path(category, custom_category: { showing: !category.showing }),
                            data: {
                              turbo_method: :patch
                            } do %>
              <% if category.showing? %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" style="width: 25px; height: 25px">
                  <path fill-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12zm13.36-1.814a.75.75 0 10-1.22-.872l-3.236 4.53L9.53 12.22a.75.75 0 00-1.06 1.06l2.25 2.25a.75.75 0 001.14-.094l3.75-5.25z" clip-rule="evenodd" />
                </svg>
              <% else %>
                <span style="display: inline-block; border-radius: 50%; height: 25px; width: 25px; background: #d6d6d6;"></span>
              <% end %>
            <% end %>
          </div>
        <% end %>
        <h3 class="text-center accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#category<%=index%>" role="button" aria-expanded="false" aria-controls="category<%=index%>">
          <%= category.name %>
        </h3>
      </div>
      <div class="collapse accordion-collapse" id="category<%=index%>">
        <h3 class="text-center"> <%= category.customised_instruction_steps.length %> steps </h3>
        <div class="d-flex flex-wrap justify-content-center"  data-controller="popover">
          <% category.customised_instruction_steps.each do |step| %>
            <div class="list-group-item d-flex flex-row align-items-center">
              <div class="m-2">
                <%= cl_image_tag step.instruction.image.key,
                    class: "instruction-thumbnail"
                %>
              </div>
              <div>
                <%= step.instruction.description[0..40] %>...
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-around">
    <%=
        link_to "Cancel", customised_instruction_path(@customised_instruction),
        method: :delete,
        class: "btn btn-outline-dark",
        data: {turbo_method: :delete, turbo_confirm: "Cancel customising instructions?"}
      %>
    <%=
      link_to "Confirm", customised_instruction_path(@customised_instruction),
      class: "btn btn-outline-dark"
    %>
  </div>
</div>

app/views/customised_instructions/show.html.erb
<div class="instructions-container">
  <div class="m-0 w-100">

    <div class="pattern-title">
      <h2 class="card-title mx-auto text-center"><%= @customised_instruction.name %> </h2>
      <%= render "shared/pattern_bar", pattern: @customised_instruction.order.pattern %>
    </div>

    <div class="accordion accordion-flush">
      <div class="d-flex justify-content-around">
        <%= link_to "Back", pattern_instructions_path(@customised_instruction.order.pattern), class: "btn btn-outline-dark" %>
        <%= link_to "Show customised instructions", customised_instruction_steps_path(@customised_instruction), class: "btn btn-outline-dark" %>
      </div>
      <% @customised_instruction_steps_by_category.each_with_index do |category, index|%>
        <% if category.showing %>
          <div class="accordion-item">
            <div class="accordion-header">
              <div class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#category<%=index%>" role="button" aria-expanded="false" aria-controls="category<%=index%>">
                <h3 class="mb-0">
                  <%= category.name %> (<%= category.customised_instruction_steps.length %> steps)
                </h3>
              </div>
            </div>
            <div class="collapse accordion-collapse"  id="category<%=index%>">
              <div class="list-group list-group-flush">
                <% category.customised_instruction_steps.each do |step| %>
                    <div class="list-group-item d-flex flex-row align-items-center">
                      <div class="m-2">
                        <%= cl_image_tag step.instruction.image.key,
                                    class: "instruction-thumbnail" %>
                      </div>
                      <div>
                          <%= step.instruction.description[0..40] %>...
                      </div>
                    </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/customised_instructions/show_instructions.html.erb
<div class="body-container">
  <div class="card m-0 w-100">
    <div class="pattern-title">
      <h2 class="card-title mx-auto text-center"><%= @pattern.title %></h2>
    </div>
    <div class="d-flex flex-wrap justify-content-center">
      <% @instructions.each do |instruction|%>
        <%= link_to pattern_steps_path(step: instruction.position) do %>
          <div class="card m-1" style="width: 10rem;">
            <%= cl_image_tag instruction.image.key,
                        class: "card-img-top img-top instructions-thumbnail",
                        height: 300,
                        crop: :fit %>
            <ul class = "list-group">
              <li class="list-group-item"><%= instruction.description[0..26] %>...</li>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/customised_instructions/show_steps.html.erb
<div class="body-container">
  <div class="card m-0 w-100">
    <div class="pattern-title">
      <h2 class="card-title mx-auto text-center"><%= @customised_instruction.order.pattern.title %> with notes</h2>
      <h4 class="card-title mx-auto text-center"><%= @customised_instruction.name %></h2>
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <% if @category == nil %>
            All
          <% else %>
            <%= @category %>
          <% end %>
        </button>
        <ul class="dropdown-menu">
            <li><%= link_to "All", customised_instruction_steps_path, class: "dropdown-item" %>
          <% @categories.each do |category| %>
            <li><a class="dropdown-item" href="/customised_instructions/<%= @customised_instruction.id %>/steps?category=<%= category %>"><%= category %></a></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="row d-flex justify-content-center main-container min-vh-100" data-controller="show-patterns">
      <div class="col d-flex justify-content-center">
        <div id="carouselExampleControls" class="carousel slide w-100">
          <div class="carousel-inner">
            <% @customised_instruction_steps.each_with_index do |instruction, index| %>
              <% if index == @step - 1 %>
                <div class="carousel-item active">
                  <div class="position-header">
                    <h5>Step <%= instruction.position %> of <%= @customised_instruction_steps.length %></h5>
                  </div>
                  <%= cl_image_tag instruction.instruction.image.key,
                      class: "d-block mx-auto carousel-image",
                      height: 800,
                      width: 500,
                      crop: :fit %>
                  <div class="step-description"><%= instruction.instruction.description %></div>
                  <% if instruction.comment %>
                    <div class="step-comment"><%=instruction.comment%></div>
                  <% else %>
                    <%= render partial: "step_comment", locals: { customised_instruction_step: instruction }%>
                  <% end %>

                </div>
              <% else %>
                <div class="carousel-item">
                  <div class="position-header">
                    <h5>Step <%= instruction.position %> of <%= @customised_instruction_steps.length %></h5>
                  </div>
                  <%= cl_image_tag instruction.instruction.image.key,
                      class: "d-block mx-auto carousel-image",
                      height: 800,
                      width: 500,
                      crop: :fit %>
                  <div class="step-description"><%= instruction.instruction.description %></div>
                  <% if instruction.comment %>
                    <div class="step-comment"><%=instruction.comment%></div>
                  <% else %>
                    <%= render partial: "step_comment", locals: {customised_instruction_step: instruction }%>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
              <i class="fa-solid fa-circle-chevron-left"></i>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
            <i class="fa-solid fa-circle-chevron-right"></i>
          </button>
    </div>
  </div>
</div>