config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: "pages#dashboard", as: "dashboard"

  resources :patterns do
    resources :reviews, only: [:new, :create, :edit, :update]
  end
  get 'patterns/:id/steps', to: "patterns#show_steps", as: "pattern_steps"
  get 'patterns/:id/instructions', to: "patterns#show_instructions", as: "pattern_instructions"

  get 'patterns/:id/instructions/new', to: "instructions#new", as: "new_instruction"
  post 'patterns/:id/instructions', to: "instructions#create", as: "create_instruction"
  post 'patterns/:id/categories', to: "categories#create", as: "create_category"

  get 'orders/:order_id/customised_instructions/new', to: "customised_instructions#new", as: "new_customised_instruction"
  post 'orders/:order_id/customised_instructions', to: "customised_instructions#create", as: "order_customised_instructions"

  resources :customised_instructions, only: [:edit, :show, :destroy] do
    resources :custom_categories, only: [:new, :create]
  end

  resources :customised_instruction_steps, only: [:edit, :update]
  get 'customised_instruction_steps/:id/', to: "customised_instruction_steps#show", as: "customised_instruction_steps"

  resources :custom_categories, only: [:update, :destroy]

  patch 'customised_instruction_steps/:id/category', to: "customised_instruction_steps#update_category"

  get 'carts/show'
  get 'carts/:id' => "carts#show", as: "cart"
  post 'carts/checkout' => "carts#checkout", as: "checkout_cart"
  delete 'carts/:id' => "carts#destroy"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  resources :reviews, only: [:destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= simple_form_for(@pattern) do |f| %>

  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :image, as: :file, input_html: { multiple: true } %>
  <%= f.input :fabric_usage, as: :file %>
  <%= f.input :sizing, as: :file %>
  <%= f.input :pdf, as: :file, input_html: { multiple: true } %>
  <%= f.input :difficulty,
            as: :radio_buttons,
            collection_wrapper_tag: 'div',
            collection_wrapper_class: 'difficulty category-wrapper',
            item_wrapper_class: 'category-item',
            input_html: {class: 'category-selector'},
            collection: Pattern::DIFFICULTY_CATEGORIES %>
  <%= f.input :instruction_format,
            as: :check_boxes,
            collection_wrapper_tag: 'div',
            collection_wrapper_class: 'instruction category-wrapper',
            item_wrapper_class: 'category-item',
            input_html: {class: 'category-selector'},
            collection: Pattern::INSTRUCTION_CATEGORIES %>
  <%= f.submit  class: "btn btn-outline-primary"%>
  <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid nav-item dropdown">

        <div>
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag "logo.png" %>
          <% end %>
        </div>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon custom-toggler"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <% unless request.original_url.end_with? 'dashboard'  %>
              <%= link_to "Dashboard", dashboard_path , class: "dropdown-item nav-link item" %>
            <% end %>
          </li>
          <li class="nav-item active item">
            <% unless request.original_url.end_with? 'patterns'  %>
            <%= link_to "Patterns", patterns_path , class: "nav-link" %>
            <% end %>
          </li>
          <%= link_to 'Cart', carts_show_path, class: "dropdown-item nav-link item" %>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item nav-link item" %>

          </li>
        <% else %>
          <li class="nav-item active item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<hr>

app/views/shared/_pattern_bar.html.erb
<div class="shadow p-2 m-2 bg-white text-dark d-flex justify-content-between align-items-center w-auto m-4">
  <div>
    <%= cl_image_tag pattern.image[0].key,
          class: "d-block",
          height: 80,
          width: 80,
          crop: :fit %>
  </div>
  <h5 class="mb-0"><%= pattern.title %></h5>
</div>