config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: "pages#dashboard", as: "dashboard"

  resources :patterns do
    resources :reviews, only: [:new, :create, :edit, :update]
  end
  get 'patterns/:id/steps', to: "patterns#show_steps", as: "pattern_steps"
  get 'patterns/:id/instructions', to: "patterns#show_instructions", as: "pattern_instructions"

  get 'patterns/:id/instructions/new', to: "instructions#new", as: "new_instruction"
  post 'patterns/:id/instructions', to: "instructions#create", as: "create_instruction"
  post 'patterns/:id/categories', to: "categories#create", as: "create_category"

  get 'orders/:order_id/customised_instructions/new', to: "customised_instructions#new", as: "new_customised_instruction"
  post 'orders/:order_id/customised_instructions', to: "customised_instructions#create", as: "order_customised_instructions"

  resources :customised_instructions, only: [:edit, :show, :destroy] do
    resources :custom_categories, only: [:new, :create]
  end

  resources :customised_instruction_steps, only: [:edit, :update]
  get 'customised_instruction_steps/:id/', to: "customised_instruction_steps#show", as: "customised_instruction_steps"

  resources :custom_categories, only: [:update, :destroy]

  patch 'customised_instruction_steps/:id/category', to: "customised_instruction_steps#update_category"

  get 'carts/show'
  get 'carts/:id' => "carts#show", as: "cart"
  post 'carts/checkout' => "carts#checkout", as: "checkout_cart"
  delete 'carts/:id' => "carts#destroy"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  resources :reviews, only: [:destroy]
end

app/views/pages/dashboard.html.erb
<link href="app/assets/stylesheets/patterns/_show.scss" rel="stylesheet">
<link href="app/assets/stylesheets/patterns/_index.scss" rel="stylesheet">


<div class="container px-4 py-5">
  <h1><%= current_user.username %> Dashboard</h1>

</div>


<div class="container-fluid mb-3">
  <h2 class="pb-2">Patterns created <%= link_to 'New pattern', new_pattern_path, class: , class: "btn btn-outline-dark" %></h2>
  <ul class = "list-group">
    <div>
        <div class = "container-fluid">
          <% @patterns_for_sale.each do |pattern| %>
            <div class="each-card shadow p-3 mb-5 ml-3 mr-3 bg-white">
              <%= cl_image_tag pattern.image[0].key, class: 'card-img-top img-top' %>
              <div class="card-body">
                <div class="card-row">
                  <p class="mb-0"><%= pattern.title %></p>
                  <p class="mb-0">$<%= pattern.price %></p>
                </div>
                <div class="card-row">
                  <div class = "icon-row">
                    <% if pattern.difficulty == "Easy" %>
                    <i class="difficulty-icon"></i>
                    <i class="difficulty-icon-light"></i>
                    <i class="difficulty-icon-light"></i>
                    <% elsif pattern.difficulty == "Medium" %>
                    <i class="difficulty-icon"></i><i class="difficulty-icon"></i>
                    <i class="difficulty-icon-light"></i>
                    <% elsif pattern.difficulty == "Hard" %>
                    <i class="difficulty-icon"></i><i class="difficulty-icon"></i><i class="difficulty-icon"></i>
                    <% end %>

                  </div>
                  <div class = "icon-row">
                    <i class="interactive-icon-filled"></i></i><i class="print-icon-filled"></i>
                  </div>

                </div>
                <div class="card-row">
                  <%# <%= link_to 'More info', pattern , class: 'btn btn-outline-dark' %>
                  <%= link_to 'Go to pattern', pattern_path(pattern) , class: 'btn btn-outline-dark bottom-link-index' %>
                  <%# <%= link_to 'More info', pattern , class: 'btn btn-outline-dark bottom-link-index' %>
                  <%= link_to 'delete', pattern_path(pattern), data: { turbo_confirm: 'Are you sure', turbo_method: :delete }, class: 'btn btn-outline-danger bottom-link-index' %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
  </ul>



</div>



<div class="container-fluid mb-3">
  <h2 class="pb-2">Patterns purchased</h2>

  <ul class = "list-group">
    <div>
        <div class = "container-fluid">
          <% @orders.each do |order| %>
            <div class="each-card shadow p-3 mb-5 ml-3 mr-3 bg-white">
              <%= cl_image_tag order.pattern.image[0].key, class: 'card-img-top img-top' %>
              <div class="card-body">
                <div class="card-row">
                  <p class="mb-0"><%= order.pattern.title %></p>
                  <p class="mb-0">$<%= order.pattern.price %></p>
                </div>
                <div class="card-row">
                  <div class = "icon-row">
                    <% if order.pattern.difficulty == "Easy" %>
                    <i class="difficulty-icon"></i>
                    <i class="difficulty-icon-light"></i>
                    <i class="difficulty-icon-light"></i>
                    <% elsif order.pattern.difficulty == "Medium" %>
                    <i class="difficulty-icon"></i><i class="difficulty-icon"></i>
                    <i class="difficulty-icon-light"></i>
                    <% elsif order.pattern.difficulty == "Hard" %>
                    <i class="difficulty-icon"></i><i class="difficulty-icon"></i><i class="difficulty-icon"></i>
                    <% end %>

                  </div>
                  <div class = "icon-row">
                    <i class="interactive-icon-filled"></i></i><i class="print-icon-filled"></i>
                  </div>

                </div>
                <div class="card-row">
                  <%# <%= link_to 'More info',  pattern , class: 'btn btn-outline-dark' %>
                  <%= link_to 'Go to pattern', pattern_path(order.pattern) , class: 'btn btn-outline-dark bottom-link-index' %>
                  <%# <%= link_to 'More info', pattern , class: 'btn btn-outline-dark bottom-link-index' %>
                  <%= link_to "Show Instructions", pattern_steps_path(order.pattern), class: "btn btn-outline-dark bottom-link-index" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
  </ul>



</div>

app/views/pages/home.html.erb
<%#
    <div class="text-wrapper">
      <div class="col-lg-6 pt-5 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center" data-aos="fade-up">
        <div>
          <h1 class='heading first-heading'>Store, organise and learn</h1>
          <h2 class='heading second-heading'>with your community, all in one place</h2>
          <%=
            link_to "Get started",
            patterns_path,
            class: "btn btn-light"
          %>
        <%# </div>
      </div>
    </div> %>
<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">The Pattern Place</h1>
        <p class="lead">Store, organise and learn with your community, all in one place!</p>
        <p>It's time to ditch the printed instructions, the disorganisation and the wasted storage space. Interactive instructions are here to improve your space and sewing experience.</p>
        <p class="lead">
          <%= link_to "Get started", patterns_path, class: "btn btn-light" %>
        </p>
    </div>
  </section>
  <div class="album py-5 bg-light">
    <div class="container text-center">
      <h2 class="lead">Featured patterns</h2>
    </div>
    <ul class = "list-group">
      <div>
        <div class = "container-fluid">
          <% @patterns.each do |pattern| %>
            <div class="each-card shadow p-3 mb-5 ml-3 mr-3 bg-white">
              <%= cl_image_tag pattern.image[0].key, class: 'card-img-top img-top' %>
              <div class="card-body">
                <div class="card-row">
                  <h5 class="mb-0"><%= pattern.title %></h5>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
     </ul>

  </div>
</main>
  <%# <main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container ">

        <div class="row">
          <div class="col-lg-6 d-flex screenshot-row" data-aos="zoom-in">
            <%# <div class="screenshot">placeholder</div> %>
            <%# <div class="screenshot"><placeholde></placeholde>r</div> %>
            <%# <%= image_tag "homepage_image1.jpg", class: "img-fluid screenshot"%>
            <%# <%= image_tag "homepage_image2.jpg", class: "img-fluid screenshot"%>
            <%# <%= image_tag "instructions.png", class: "img-fluid screenshot"%>
          <%# </div>
          <div class="col-lg-6 d-flex flex-column justify-contents-center" data-aos="fade-left">
            <div class="content pt-4 pt-lg-0">
              <h3>Your personal library of design and fabric patterns</h3>
              <ul>
                <li class="d-flex align-items-center"><i class="flower-icon mr-1"></i> Watch and follow creators you love </li>
                <li class="d-flex align-items-center"><i class="flower-icon"></i> Step by step instructions in a digital format </li>
                <li class="d-flex align-items-center"><i class="flower-icon"></i> No more giant printouts </li>
              </ul>
              <p class="fst-italic">
                All in one space
              </p>
            </div>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->
  </main>  %>