config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: "pages#dashboard", as: "dashboard"

  resources :patterns do
    resources :reviews, only: [:new, :create, :edit, :update]
  end
  get 'patterns/:id/steps', to: "patterns#show_steps", as: "pattern_steps"
  get 'patterns/:id/instructions', to: "patterns#show_instructions", as: "pattern_instructions"

  get 'patterns/:id/instructions/new', to: "instructions#new", as: "new_instruction"
  post 'patterns/:id/instructions', to: "instructions#create", as: "create_instruction"
  post 'patterns/:id/categories', to: "categories#create", as: "create_category"

  get 'orders/:order_id/customised_instructions/new', to: "customised_instructions#new", as: "new_customised_instruction"
  post 'orders/:order_id/customised_instructions', to: "customised_instructions#create", as: "order_customised_instructions"

  resources :customised_instructions, only: [:edit, :show, :destroy] do
    resources :custom_categories, only: [:new, :create]
  end

  resources :customised_instruction_steps, only: [:edit, :update]
  get 'customised_instruction_steps/:id/', to: "customised_instruction_steps#show", as: "customised_instruction_steps"

  resources :custom_categories, only: [:update, :destroy]

  patch 'customised_instruction_steps/:id/category', to: "customised_instruction_steps#update_category"

  get 'carts/show'
  get 'carts/:id' => "carts#show", as: "cart"
  post 'carts/checkout' => "carts#checkout", as: "checkout_cart"
  delete 'carts/:id' => "carts#destroy"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  resources :reviews, only: [:destroy]
end

app/models/pattern.rb
class Pattern < ApplicationRecord
  INSTRUCTION_CATEGORIES = ["Print", "Interactive"]

  DIFFICULTY_CATEGORIES = ["Easy", "Medium", "Hard"]

  belongs_to :user
  has_many :line_items, dependent: :destroy
  validates :difficulty,
            acceptance:
            { accept: DIFFICULTY_CATEGORIES }
  validates :instruction_format,
            acceptance:
            { accept: INSTRUCTION_CATEGORIES }
  has_many_attached :image
  has_one_attached :sizing
  has_one_attached :fabric_usage
  has_many_attached :pdf
  has_many :orders
  has_many :instructions
  has_many :reviews, through: :orders
  has_many :categories
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  def index
    if params[:query].present?
      @patterns = Pattern.where("title ILIKE :query OR description ILIKE :query", query: "%#{params[:query]}%")
    else
      @patterns = Pattern.all
    end
  end

  def show
    @pattern = Pattern.find(params[:id])
    @ordered_pattern = @pattern.orders.find_by(user: current_user)
    @reviews = @pattern.reviews
  end

  def new
    @pattern = Pattern.new
  end

  def create
    @pattern = Pattern.new(pattern_params)
    @pattern.user = current_user
    if @pattern.save
      redirect_to dashboard_path, notice: 'Your pattern has been created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @pattern = Pattern.find(params[:id])
    if @pattern.delete
      redirect_to dashboard_path, notice: 'Your pattern has been deleted'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show_instructions
    @pattern = Pattern.find(params[:id])
    @instructions = @pattern.instructions.order('position ASC')
    @customised_instruction = CustomisedInstruction.new
    @order = Order.find_by(user: current_user, pattern: @pattern)
  end

  def show_steps
    if params[:step].present?
      @step = params[:step].to_i
    else
      @step = 1
    end
    @pattern = Pattern.find(params[:id])
    @instructions = []
    @categories = @pattern.categories.order('position ASC')
    # note - N + 1 query - inherently bad, trying to find a better way of doing it
    @categories.each do |category|
      category.instructions.order('position ASC').each do |instruction|
        @instructions << instruction
      end
    end
  end

  private

  def pattern_params
    params.require(:pattern).permit(:title, :description, :price, :difficulty, :fabric_usage, :sizing, image: [], pdf: [])
  end
end

app/views/patterns/index.html.erb
<div class="index-patterns">

<div class="container-fluid">
    <%= form_with url: patterns_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Eg. dress"
    %>
    <%= submit_tag "Search", class: "btn btn-outline-dark" %>
  <% end %>
</div>
  <ul class = "list-group">
    <div>
        <div class = "container-fluid">
          <% @patterns.each do |pattern| %>
            <div class="each-card shadow p-3 mb-5 ml-3 mr-3 bg-white">
              <%= cl_image_tag pattern.image[0].key, class: 'card-img-top img-top' %>
              <div class="card-body">
                <div class="card-row">
                  <p class="mb-0"><%= pattern.title %></p>
                  <p class="mb-0">$<%= pattern.price %></p>
                </div>
                <div class="card-row">
                  <div class = "icon-row">
                    <% if pattern.difficulty == "Easy" %>
                    <i class="difficulty-icon"></i>
                    <i class="difficulty-icon-light"></i>
                    <i class="difficulty-icon-light"></i>
                    <% elsif pattern.difficulty == "Medium" %>
                    <i class="difficulty-icon"></i><i class="difficulty-icon"></i>
                    <i class="difficulty-icon-light"></i>
                    <% elsif pattern.difficulty == "Hard" %>
                    <i class="difficulty-icon"></i><i class="difficulty-icon"></i><i class="difficulty-icon"></i>
                    <% end %>
                  </div>
                  <div class = "icon-row">
                    <i class="interactive-icon-filled"></i></i><i class="print-icon-filled"></i>
                  </div>
                </div>
                <div class="card-row">
                  <%= link_to 'More info', pattern , class: 'btn btn-outline-dark' %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
  </ul>



</div>

app/views/patterns/new.html.erb
<div class="container px-5">
  <h1>New Pattern</h1>

  <%= render 'shared/form' %>
</div>

app/views/patterns/show.html.erb
<div class="d-flex justify-content-around">
  <%= link_to 'Back to search', patterns_path , class: "btn btn-outline-dark"%>
  <% if Order.find_by(pattern_id: @pattern.id, user: current_user) %>
    <%= link_to "Show Instructions", pattern_steps_path, class: "btn btn-outline-dark" %>
  <% elsif LineItem.find_by(pattern_id: @pattern.id, user: current_user) %>
    <div class="btn btn-outline-dark"> Already in cart</div>
  <% else %>
    <%= button_to "Add to cart", line_items_path(:pattern_id => @pattern.id), class: "btn btn-outline-dark" %>
  <% end %>
</div>
<br>
<div class="patterns-container">
  <div class="m-0 w-100">
    <div class="row d-flex justify-content-center main-container" data-controller="show-patterns">
      <div class="col d-flex justify-content-center">
        <div id="carouselExampleControls" class="carousel slide w-100" data-bs-ride="carousel">
          <div class="carousel-inner">
            <% @pattern.image.each_with_index do |image, index| %>
              <% if index == 0 %>
                <div class="carousel-item active">
                  <%= cl_image_tag image.key,
                      class: "d-block mx-auto carousel-image",
                      height: 400,
                      width: 500,
                      crop: :fit %>
                </div>
              <% else %>
                <div class="carousel-item">
                  <%= cl_image_tag image.key,
                      class: "d-block mx-auto carousel-image",
                      height: 400,
                      width: 500,
                      crop: :fit %>
                </div>
              <% end %>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          </button>
        </div>
      </div>
      <div class="container">
        <div class="text-body">
          <ul class="list-group list-group-flush ">
            <div class="d-flex justify-content-between mt-2">
              <h4 class="card-title"><%= @pattern.title %></h4>
              <h4 class="card-title">$<%= sprintf('%.2f', @pattern.price) %></h4>
            </div>
            <hr>
            <li class="list-group-item p-0 my-2"><strong></strong><%= @pattern.description %></li>
            <div class="icons-body">
              <div class="card-row">
                <div class="title-section-second">
                  <h4 class="my-2"><strong>Difficulty level </strong></h4>
                </div>
                <div class = "icon-row">
                  <% if @pattern.difficulty == "Easy" %>
                  <i class="difficulty-icon"></i>
                  <i class="difficulty-icon-light"></i>
                  <i class="difficulty-icon-light"></i>
                  <% elsif @pattern.difficulty == "Medium" %>
                  <i class="difficulty-icon"></i><i class="difficulty-icon"></i>
                  <i class="difficulty-icon-light"></i>
                  <% elsif @pattern.difficulty == "Hard" %>
                  <i class="difficulty-icon"></i><i class="difficulty-icon"></i><i class="difficulty-icon"></i>
                  <% end %>
                </div>
              </div>
              <div class="card-row">
                <div class="title-section">
                  <h4 class="my-2"><strong>File inclusions </strong></h4>
                </div>
                <div class = "icon-row">
                  <i class="interactive-icon"></i></i><i class="print-icon"></i>
                </div>
              </div>
              <div class="accordion accordion-flush" id="accordionPattern">
                <% if @pattern.fabric_usage != nil %>
                  <div class="accordion-item mt-3 mb-3">
                    <div class="accordion-header">
                      <div class="accordion-button collapsed p-0" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFabric" aria-expanded="false" aria-controls="collapseFabric">
                        <h4><strong>Fabric information </strong></h4>
                      </div>
                    </div>
                    <div id="collapseFabric" class="accordion-collapse collapse" aria-labelledby="collapseFabric" data-bs-parent="#accordionPattern">
                    <%= cl_image_tag @pattern.fabric_usage.key,
                      class: "rounded d-block mx-auto my-2 w-100",
                      width: 400,
                      crop: :fit %>
                  </div>
                </div>
                <% end %>
                <% if @pattern.sizing != nil %>
                  <div class="accordion-item mt-3 mb-3">
                    <div class="accordion-header ">
                      <div class="accordion-button collapsed p-0" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSizing" aria-expanded="false" aria-controls="collapseSizing">
                        <h4><strong>Size chart </strong></h4>
                      </div>
                    </div>
                    <div id="collapseSizing" class="accordion-collapse collapse" aria-labelledby="collapseSizing" data-bs-parent="#accordionPattern">
                    <%= cl_image_tag @pattern.sizing.key,
                      class: "rounded d-block mx-auto my-2 w-100",
                      width: 400,
                      crop: :fit %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </ul>
        </div>
      </div>

    </div>

    <div class="pattern_heading">

    <% if !@pattern.reviews.empty? %>
      <h2>Reviews</h2>
    <% end %>
    <% if @ordered_pattern %>

      <% if !@ordered_pattern.review %>
        <%= link_to 'Add a review', new_pattern_review_path(@pattern), class: 'btn btn-outline-dark btn-lg btn-block', style: "width:100%;" %>
      <% end %>
    <% end %>

  <ul class="list-group">
  <% @reviews.each do |review| %>
    <li class="list-group-item">
    <% name = review.user.email %>
    <% capitalize_name = name[0, name.index('@')].capitalize  %>
    <strong><%= "#{capitalize_name}: " %></strong><%= review.content %>
    <% if review.user == current_user %>
      <%= link_to 'Edit', edit_pattern_review_path(@pattern, review) %>
      <%= link_to 'Delete', review_path(review), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
    <% end %>
    </li>

  <% end %>
  </ul>

</div>
<br><br><br>

</div>

app/views/patterns/show_instructions.html.erb
<div class="instructions-container">
  <div class="m-0 w-100">
    <% if @order %>
      <div class="pattern-title">
        <h2 class="card-title mx-auto text-center">Interactive instructions</h2>
          <%= render "shared/pattern_bar", pattern: @pattern %>
      </div>
      <div class="d-flex justify-content-around">
        <%= link_to "Back", pattern_steps_path(@pattern), class:"btn btn-outline-dark" %>
        <button class="btn btn-outline-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseCopies" aria-expanded="false" aria-controls="collapseCopies">
          Your copies
        </button>
        <button class="btn btn-outline-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
          Create instructions
        </button>
      </div>
      <div class="collapse" id="collapseCopies">
        <div class="list-group list-group-flush">
            <li class="list-group-item"> <h5>Your copies</h5> </li>
            <% @order.customised_instructions.each do |customised_instruction|%>
              <%= link_to customised_instruction_path(customised_instruction), style: 'text-decoration: none;' do%>
                <li class="list-group-item d-flex justify-content-between">
                  <%=customised_instruction.name%>
                  <%=
                    link_to customised_instruction_path(customised_instruction),
                    method: :delete,
                    data: {turbo_method: :delete, turbo_confirm: "Cancel customising instructions?"} do
                  %>
                  <i class="trashcan-icon"></i>
                  <% end %>
                </li>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="collapse" id="collapseExample">
        <div class="p-3">
          <%= simple_form_for [@order, @customised_instruction] do |f| %>
            <div class="d-flex justify-content-around align-items-center">
              <%= f.input :name, label: false, placeholder:'Name', wrapper: false  %>
              <%= f.submit "Create new copy", class: "btn btn-outline-dark" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="accordion accordion-flush">
        <h3 class="mt-4 mb-1 text-center"> Sections </h3>
        <% @pattern.categories.each_with_index do |category, index|%>
          <div class="accordion-item">
            <div class="accordion-header">
              <div class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#category<%=index%>" role="button" aria-expanded="false" aria-controls="category<%=index%>">
                <h3 class="mb-0">
                  <%= category.name %> (<%= category.instructions.length %> steps)
                </h3>
              </div>
            </div>
            <div class="collapse accordion-collapse"  id="category<%=index%>">
              <div class="list-group list-group-flush">
                <% category.instructions.each do |instruction| %>
                  <div class="list-group-item d-flex flex-row align-items-center">
                    <div class="m-2">
                      <%= cl_image_tag instruction.image.key,
                          class: "instruction-thumbnail"
                      %>
                    </div>
                    <div><%= instruction.description[0..40] %>...</div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="pattern-title">
        You need to purchase this pattern in order to see the instructions
      </div>
    <% end %>
  </div>
</div>

app/views/patterns/show_steps.html.erb
<div class="instructions-container">
    <div class="pattern-title">
        <h2 class="card-title mx-auto text-center">Interactive instructions</h2>
          <%= render "shared/pattern_bar", pattern: @pattern %>
      </div>
    <div class="dropdown">
      <div class="d-flex justify-content-around mb-3">
        <%= link_to "Back", pattern_path(@pattern), class: "btn btn-outline-dark" %>
        <%= link_to "Customise instructions", pattern_instructions_path(@pattern), class: "btn btn-outline-dark" %>
      </div>
      <ul class="dropdown-menu">
        <% @pattern.categories.each do |category| %>
          <% if category == @category %>
            <li>
              <%= link_to category.name, pattern_steps_path(@pattern, category_position: category.position), class: "dropdown-item active" %>
            </li>
          <% else %>
            <li>
              <%= link_to category.name, pattern_steps_path(@pattern, category_position: category.position), class: "dropdown-item" %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <div class="d-flex justify-content-center step-container" data-controller="show-patterns">
      <div class="col d-flex justify-content-center">
        <div id="carouselExampleControls" class="carousel slide w-100">
          <div class="carousel-inner">
            <% @instructions.each_with_index do |step, index| %>
              <% if index == @step - 1 %>
                <div class="carousel-item active">
                  <div class="d-flex justify-content-center">
                    <h5><%= step.category.name %></h5>
                  </div>
                  <%= cl_image_tag step.image.key,
                      class: "d-block mx-auto carousel-image",
                      height: 800,
                      width: 500,
                      crop: :fit %>
                  <div class="step-description"><%= step.description %></div>
                </div>
              <% else %>
                <div class="carousel-item">
                  <div class="d-flex justify-content-center">
                    <h5><%= step.category.name %></h5>
                  </div>
                  <%= cl_image_tag step.image.key,
                      class: "d-block mx-auto carousel-image",
                      height: 800,
                      width: 500,
                      crop: :fit %>
                  <div class="step-description"><%= step.description %></div>
                </div>
              <% end %>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          </button>
    </div>
</div>